# Generated by Django 3.0.4 on 2020-07-28 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Rubrics')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['published'], 'verbose_name': 'News', 'verbose_name_plural': 'Newses'},
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='null', verbose_name='Main Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='null', max_length=300, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='news',
            name='rubric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Rubric'),
            preserve_default=False,
        ),
    ]
