# Generated by Django 3.0.4 on 2020-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test of adding a description field into the model Items'),
            preserve_default=False,
        ),
    ]
