# Generated by Django 3.0.4 on 2020-07-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200727_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/news/Camping.jpg', upload_to='media/items'),
        ),
    ]
