# Generated by Django 3.0.4 on 2020-08-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200807_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SP', 'Spining'), ('FD', 'Feeder'), ('FL', 'Float'), ('WN', 'Winter'), ('SA', 'Sea'), ('CR', 'Carp'), ('TR', 'Tourism'), ('EQ', 'Equipment')], max_length=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.Item')),
            ],
        ),
    ]
