# Generated by Django 3.0.4 on 2020-08-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200807_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ItemCategory'),
        ),
    ]
