# Generated by Django 3.0.4 on 2020-08-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200807_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
