# Generated by Django 3.0.4 on 2020-08-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200807_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='title_Voxa',
        ),
    ]
